name: Workflow For Main page
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:

jobs:
  run-e2es:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci && npx playwright install && npm install @playwright/test
      - name: Run end-to-end tests
        run: npx playwright test --workers=4
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  run-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm ci && npm install
      - name: 'Coverage Test'
        run: npx vitest --coverage.enabled true
      - name: 'Report Coverage'
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
      - name: Run unit tests
        run: npm run test
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}
      - name: Upload Vitest Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: vitest-report
          path: test-results/index.html
          retention-days: 30


