name: New Workflow 2
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
jobs:

#  deploy-to-vercel:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Install Vercel CLI
#        run: npm install --global vercel@latest
#      - name: Pull Vercel Environment Information
#        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
#      - name: Build Project Artifacts
#        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
#      - name: Deploy Project Artifacts to Vercel
#        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
#      - name: Assign Domain in Vercel
#        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
#  run-e2es:
#    runs-on: ubuntu-latest
#    needs: deploy-to-vercel
#    steps:
#      - uses: actions/checkout@v2
#      - name: Install dependencies
#        run: npm ci && npx playwright install && npm install @playwright/test
#      - name: Run tests
#        run: npx playwright test
#        env:
#          BASE_URL: ${{ github.event.deployment_status.environment_url }}
  run-unit:
    runs-on: ubuntu-latest
    needs: deploy-to-vercel
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm ci && npm install
      - name: Run tests
        run: npm run test
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}

