name: New Workflow 2
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
jobs:
  run-e2es:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci && npx playwright install && npm install @playwright/test
      - name: Run end-to-end tests
        run: npx playwright test --workers=4
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}

  run-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm ci && npm install
      - name: Run unit tests
        run: npm run test
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}
